# Configurações gerais (fallback caso a raridade não defina algo)
level_system:
  base_xp: 100
  xp_multiplier: 1.5
  damage_increase_per_level: 1.2

# Configurações das raridades
rarities:
  COMMON:
    name: "§7Comum"
    damage_multiplier: 1.0
    base_xp: 80
    xp_multiplier: 1.3
    damage_increase_per_level: 1.0
  RARE:
    name: "§aRaro"
    damage_multiplier: 1.2
    base_xp: 100
    xp_multiplier: 1.5
    damage_increase_per_level: 1.2
  EPIC:
    name: "§5Épico"
    damage_multiplier: 1.5
    base_xp: 120
    xp_multiplier: 1.7
    damage_increase_per_level: 1.5
  LEGENDARY:
    name: "§6Lendário"
    damage_multiplier: 2.0
    base_xp: 150
    xp_multiplier: 2.0
    damage_increase_per_level: 2.0
  MYTHIC:
    name: "§dMítico"
    damage_multiplier: 2.5
    base_xp: 200
    xp_multiplier: 2.5
    damage_increase_per_level: 3.0

# Define a quantidade de XP que o pet ganha ao matar uma entidade.
xp_values:
  default: 10
  ZOMBIE: 15
  SKELETON: 15
  SPIDER: 12
  ENDERMAN: 25
  ENDER_DRAGON: 1000
